apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cdelashmutt
spec:
  profile:
    displayName: Chris DeLashmutt
    email: cdelashmutt@vmware.com
    picture: https://www.gravatar.com/avatar/8b3c258bf02ddf159a968d6b61f57d69
  memberOf: [tanzu-se-southeast-team]
