apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nitashav
spec:
  profile:
    displayName: Nitasha Verma
    email: nitashav@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [tanzu-se-southeast-team, blockchain-api/blockchain-api-team]
